export const JOB_STATUS = {
  NORMAL: 0,
  POPULAR: 1,
  URGENT: 2,
  HOT: 3,
  SUPER_HOT: 4,
  EXCLUSIVE: 5,
  LIMITED_TIME: 6,
};
export const JOB_STATUS_NAME = {
  [JOB_STATUS.NORMAL]: "NORMAL",
  [JOB_STATUS.POPULAR]: "POPULAR",
  [JOB_STATUS.URGENT]: "URGENT",
  [JOB_STATUS.HOT]: "HOT",
  [JOB_STATUS.SUPER_HOT]: "SUPER_HOT",
  [JOB_STATUS.EXCLUSIVE]: "EXCLUSIVE",
  [JOB_STATUS.LIMITED_TIME]: "LIMITED_TIME",
};
//store in MongoDB
export const JOB_FEES = {
  [JOB_STATUS.POPULAR]: 100,
  [JOB_STATUS.URGENT]: 200,
  [JOB_STATUS.HOT]: 300,
  [JOB_STATUS.SUPER_HOT]: 400,
  [JOB_STATUS.EXCLUSIVE]: 500,
  [JOB_STATUS.LIMITED_TIME]: 600,
};
